const articleData=[
    {
        id:1,
        img1:'./img/16.png',
        textA:'#只有撒贝宁敢在央视这么放肆# 1',
        textB:'看了央视的中秋晚会探班直播，我真的会被撒贝宁给笑死。。。',
        img2:'./img/太阳.png',
        authorA:'央视新闻',
        authorB:'2021.2.2',
        span1:'1234',
        span2:'5678',
        span3:'9876',
    },
    {
        id:2,
        img1:'./img/16.png',
        textA:'#只有撒贝宁敢在央视这么放肆# 2',
        textB:'看了央视的中秋晚会探班直播，我真的会被撒贝宁给笑死。。。',
        img2:'./img/太阳.png',
        authorA:'央视新闻',
        authorB:'2021.2.2',
        span1:'1234',
        span2:'5678',
        span3:'9876',
    },
    {
        id:3,
        img1:'./img/16.png',
        textA:'#只有撒贝宁敢在央视这么放肆# 3',
        textB:'看了央视的中秋晚会探班直播，我真的会被撒贝宁给笑死。。。',
        img2:'./img/太阳.png',
        authorA:'央视新闻',
        authorB:'2021.2.2',
        span1:'1234',
        span2:'5678',
        span3:'9876',
    },
    {
        id:4,
        img1:'./img/16.png',
        textA:'#只有撒贝宁敢在央视这么放肆# 4',
        textB:'看了央视的中秋晚会探班直播，我真的会被撒贝宁给笑死。。。',
        img2:'./img/太阳.png',
        authorA:'央视新闻',
        authorB:'2021.2.2',
        span1:'1234',
        span2:'5678',
        span3:'9876',
    },
    {
        id:5,
        img1:'./img/16.png',
        textA:'#只有撒贝宁敢在央视这么放肆# 5',
        textB:'看了央视的中秋晚会探班直播，我真的会被撒贝宁给笑死。。。',
        img2:'./img/太阳.png',
        authorA:'央视新闻',
        authorB:'2021.2.2',
        span1:'1234',
        span2:'5678',
        span3:'9876',
    },
    {
        id:6,
        img1:'./img/16.png',
        textA:'#只有撒贝宁敢在央视这么放肆# 6',
        textB:'看了央视的中秋晚会探班直播，我真的会被撒贝宁给笑死。。。',
        img2:'./img/太阳.png',
        authorA:'央视新闻',
        authorB:'2021.2.2',
        span1:'1234',
        span2:'5678',
        span3:'9876',
    },
]
